# Generated by Django 5.0.5 on 2024-05-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='etapa',
            fields=[
                ('id_etapa', models.BigAutoField(primary_key=True, serialize=False)),
                ('etapa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='prospecto',
            fields=[
                ('id_prospecto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha_ingreso', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechTestAPP.cliente')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechTestAPP.estado')),
                ('etapa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechTestAPP.etapa')),
            ],
        ),
    ]
