# Generated by Django 5.0.5 on 2024-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechTestAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombreusuario')),
                ('password', models.CharField(max_length=60, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
