# Generated by Django 5.0.5 on 2024-05-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechTestAPP', '0003_alter_usuarios_managers_usuarios_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
