# Generated by Django 5.0.5 on 2024-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechTestAPP', '0004_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombreusuario'),
        ),
    ]
