version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: techtest_arkenco
      MYSQL_USER: TechTest
      MYSQL_PASSWORD: User1029
    ports:
      - "3307:3306"  # Asegúrate de no tener conflictos con el puerto 3306 en tu host

  app:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      MYSQL_DATABASE: techtest_arkenco
      MYSQL_USER: TechTest
      MYSQL_PASSWORD: User1029
